name: build
permissions:
  contents: write
on:
  schedule:
    - cron: '0 10 * * 1-5'
  push:
    paths:
      - '.github/workflows/build_linux.yml'
  workflow_dispatch: {}

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup premake
        uses: abel0b/setup-premake@v2.2
        with:
          version: 5.0.0-beta1
      - name: Build
        run: |
            chmod +x build.sh
            ./build.sh
      - name: Build Rust Project
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          cd rust
          cargo build --release
      - name: Copy DLLs
        run: |
          mkdir -p ./bin/Linux
          cp -f ./cpp/build/bin/Release/*.so ./bin/Linux
          for file in ./rust/target/release/lib*.so; do
            cp -f "$file" "$dir$(basename "$file" | sed 's/^lib//')"
          done
      - uses: actboy168/action-zip@main
        id: zip
        with:
          name: laux-linux
          path: |
            bin/
            README.md
      - uses: softprops/action-gh-release@v1
        with:
          name: build
          tag_name: build
          fail_on_unmatched_files: true
          files: '${{  steps.zip.outputs.output }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
